### ISSUE TITLE
Really bad spectate mode. Avg. FPS 1. (with video proof)

### ISSUE THREAD

**Issue by aiiman** [SNSA/NEXT#103]
The FPS when playing is always 60 FPS. No drops whatsoever.

The average FPS in spectate mode is 1 FPS. It freezes only when the cell splits or feeds (w). Rather than that (no split and feed), it runs smoothly (50-60 FPS).

Video proof. Video is in 60 FPS.
Video 1 [https://youtu.be/Hg9YKjvqseY](url)
Video 2 [https://youtu.be/YW4ZOfILJuM](url)

**Comment by heroandtn3** [comment]
duplicate #95
