### ISSUE TITLE
better animations

### ISSUE THREAD

**Issue by henopied** [SNSA/NEXT#29]
I think the client should use a better method for animating cell position changes.

**Comment by heroandtn3** [comment]
It seems that the cell animates from small size to the actual size.

**Comment by henopied** [comment]
[https://github.com/DnAp/Agar.io-Reverse-Engineering/blob/master/main_out.js#L996] (this) should help

**Comment by heroandtn3** [comment]
@henopied I tried it, but the animation when I move my cell gets jerky 

```
      const now = Date.now();
      var A = (now - this.frTime) / 120;
      A = 0 > A ? 0 : 1 < A ? 1 : A;
      A = A * A * (3 - 2 * A);
      return ~~(A * (this.toVal - this.frVal) + this.frVal);
```

**Comment by heroandtn3** [comment]
Ah, it seems that this should work:

      const now = Date.now();
      var A = (now - this.frTime) / 120;
      A = 0 > A ? 0 : 1 < A ? 1 : A;
      return ~~(A * (this.toVal - this.frVal) + this.frVal);

**Comment by henopied** [comment]
yea, what I found was that it is best to change the timeout from 100 to 120 (that seemed to fix the jerkiness.)
