### ISSUE TITLE
How do I install this extension?

### ISSUE THREAD

**Issue by aiiman** [SNSA/NEXT#34]
I am a total newb. I have Node.js. How do I install this extension? I installed next.chrome.js in Tampermonkey on my chrome but it only shows a white screen when on agar.io.

**Comment by acydwarp** [comment]
Run `npm install` and `jspm install`. This will install all needed dependencies.

Once all dependencies have been installed, you can run `gulp dev`. This generates the bundled files and launches a local server on port 8080 through browser-sync. Then, you can visit agar.io.

Please note that it's very early stages and you may come across a few bugs. Let us know if you find anything.

**Comment by heroandtn3** [comment]
@aiiman our instruction is just for testing, please wait until we release our first version of NEXT

**Comment by anatrey** [comment]
I have issues with npm. jspm is allright. 

~ npm WARN install Couldn't install optional dependency: Unsupported
~  throw err;
    ^

Error: Cannot find module 'readable-stream'
~ npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1 (this repeats one time)
~ npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp re                                                                                                                                                                                               build`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
npm WARN EPACKAGEJSON NEXT@0.0.1 No repository field.

I'm noob like aiiman too. Thanks for this!

**Comment by aiiman** [comment]
I literally have no idea how to do this. Can you guide me through a step-by-step instruction?

**Comment by aiiman** [comment]
@acydwarp All I did was open cmd and cd the directory of the extension's folder. Then, type npm install and it did something. Did the same for jspm, nothing happened. I really don't know anything.

**Comment by henopied** [comment]
First install [nodejs](nodejs.org) stable on your computer (restart cmd.) Then `cd` to where you have unzipped your `NEXT` folder `cd NEXT` if you are not already in that folder. Then do `npm install` then you will want to run `npm install -g jspm` and you will want to run `npm install -g gulp`. At that point you may need to restart your cmd. Then `cd `back to `NEXT` and run `jspm install` and after that is completed you will want to install the userscript (you could do that at any time.) Lastly you will want to run `gulp dev` in that directory whenever you want to be able to use the extension.

**Comment by aiiman** [comment]
@henopied Thank you! Your instructions worked. I didn't know about npm install -g jspm and npm install -g gulp.

@acydwarp The extension's fps is super-smooth! But the cells roundness is not smooth. And, I think it's better to use the vanilla agar.io's font.

**Comment by anatrey** [comment]
Thanks to all, its running now.
