### ISSUE TITLE
Can't go the NEXT

### ISSUE THREAD

**Issue by bean07** [SNSA/NEXT#39]
![image](https://cloud.githubusercontent.com/assets/10783527/12880593/e056568e-ce74-11e5-89bf-7e2dce922d0e.png)
it only show like this!

**Comment by xzfc** [comment]
See https://github.com/SNSA/NEXT/issues/34#issuecomment-180808084

**Comment by bean07** [comment]
I view it i install all and run go agar and still have that bugs

**Comment by xzfc** [comment]
I see you're using http://localhost:8080. You should use http://agar.io/
instead.

**Comment by bean07** [comment]
I waked wrong but i still cant run!

**Comment by anatrey** [comment]
It's not finish yet. Try changing your region and put autospawn. Press spawn. Try several times, that works for me.

**Comment by bean07** [comment]
it only run to:Serving file ./build and dont run next!

**Comment by heroandtn3** [comment]
@bean07 please use this userscript http://snsa.github.io/NEXT/next.chrome.user.js
