### ISSUE TITLE
connector

### ISSUE THREAD

**Issue by henopied** [SNSA/NEXT#40]
The connector shouldn't be a class you should just port pulviscriptor's server.js to use xmlhttprequest like [this](https://gist.github.com/henopied/d4bb32ed718441473765) to avoid the odd callback system you have now.

**Comment by xzfc** [comment]
It should be easily unit-testable and should have state (to handle situations like, eg. when user clicks "Join FFA" twice, first request should be cancelled).
So, using class is preferable.

**Comment by heroandtn3** [comment]
1. We will use Promise instead of callback.
2. I do not think stateful connector is a good idea, keep it simple as a utility to get IP address and token of an Agar room.

**Comment by heroandtn3** [comment]
The connector has been removed in #76
