### ISSUE TITLE
How to install this please help.

### ISSUE THREAD

**Issue by Rubik022** [SNSA/NEXT#42]
Hello I already installed node.js and i go to "command prompt" then 'npm install'?

and it says : 
![image](https://cloud.githubusercontent.com/assets/17194954/13003568/3e64e80a-d1b1-11e5-84a0-545731dc4e7e.png)

Then i cant "jspm install" and "gulp dev" i already installed next.chrome.js

does anyone can teach me step by step? pleaseeee

**Comment by heroandtn3** [comment]
@Rubik022 you must [download](https://github.com/SNSA/NEXT/archive/master.zip) the repository then run those commands inside the project folder.

**Comment by Rubik022** [comment]
@heroandtn3 What do you mean?

**Comment by heroandtn3** [comment]
I mean you need to download the project (https://github.com/SNSA/NEXT/archive/master.zip).

**Comment by Rubik022** [comment]
I already download it and its still not working.

**Comment by heroandtn3** [comment]
Extract the zip file then run `npm install` inside the extracted folder.

**Comment by Rubik022** [comment]
I dont see any run inside folder.

**Comment by heroandtn3** [comment]
https://github.com/SNSA/NEXT/issues/34

**Comment by Rubik022** [comment]
Can you take screen how you do that?

**Comment by heroandtn3** [comment]
Please spend time to read what I commented.

**Comment by Rubik022** [comment]
This shows when i "npm install"
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'
npm WARN Administrator No description
npm WARN Administrator No respository field
npm WARN Administrator No README data
npm WARN Administrator No license field.

**Comment by heroandtn3** [comment]
@Rubik022 please use this userscript to install http://snsa.github.io/NEXT/next.chrome.user.js
