### ISSUE TITLE
Automatically deploy to somewhere

### ISSUE THREAD

**Issue by heroandtn3** [SNSA/NEXT#43]
I think it's nice if we deploy this to somewhere to help people easier to try NEXT. 

Github already supports [automating deployment](https://developer.github.com/guides/automating-deployments-to-integrators/) so it's nice if we can automatically deploy NEXT to an external serrver on each commit or merge of the `master` branch.

Update: this post is useful http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

- [x] Update userscript to use with production and dev purpose
- [x] Create GH page to deploy
- [x] Update travis to deploy automatically

**Comment by Rubik022** [comment]
Why not just release the beta version please i want to try it but i dont know how.

**Comment by heroandtn3** [comment]
This is blocked by #12
