### ISSUE TITLE
Ignore config.js file

### ISSUE THREAD

**Issue by heroandtn3** [SNSA/NEXT#52]
This file is auto generated by jspm, so we don't need it to be included in the repo

**Comment by xzfc** [comment]
[jspm docs] says otherwise:
> The config.js file is updated with the version information and the version is locked down, this configuration file itself forming the lock, which should be added to version control.

We don't want extension to be broken if some of dependencies updates in incompatible way.

[jspm docs]: http://jspm.io/docs/getting-started.html

**Comment by heroandtn3** [comment]
@xzfc you are right, I'm going to revert this PR
