### ISSUE TITLE
Use newer node version

### ISSUE THREAD

**Issue by xzfc** [SNSA/NEXT#59]
It seems that my PR #58 travis test failed due to old version of node (v0.10.42) used by travis. It works fine with my node v5.6.0.
Some limitations of node v0.10.42: no `const` in strict mode, no arrow functions.
To make unit testing possible, we should switch to newer node version. This decision includes upgrading node on developers' systems, and setting version used by travis [1].

[1]: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against

**Comment by heroandtn3** [comment]
Agree, let's do it.

**Comment by xzfc** [comment]
Closed @ #58.
