### ISSUE TITLE
Node js cant install

### ISSUE THREAD

**Issue by Rubik022** [SNSA/NEXT#60]
Hello I want to ask how do you run "npm install" and what it shows to you can you give me screen.

it spams "NPM WARN" to me. can someone help please.

**Comment by heroandtn3** [comment]
@Rubik022 please use this userscript to install http://snsa.github.io/NEXT/next.chrome.user.js

**Comment by Rubik022** [comment]
@heroandtn3  I already did it and it always show like "npm WARN"

**Comment by heroandtn3** [comment]
@Rubik022 Please! You do not need to run `npm install`, just install the userscript then go to http://agar.io

**Comment by Rubik022** [comment]
@heroandtn3 It stucked at white screen.

**Comment by oxygar** [comment]
@heroandtn3 hey hero, can u help me ;( http://vndot-agarvn.rhcloud.com:8000 gimme file inside the link, i give up ;(, God Bless You :) u can send the file to : muhammad_alif_61@yahoo.co.id ;)
