### ISSUE TITLE
LeaderBoard Spasm

### ISSUE THREAD

**Issue by tobq** [SNSA/NEXT#61]
A leaderboard is generated once you connect to a server, but once you leave that server the leaderboard for that server is kept, along with the newly generated leaderboard of the current server. So both server leaderboards are being generated at displayed making for a spasticated leaderboard in which the leaderboards keep switching from one to another.

- Clear old leaderboard once connected to new server.

**Comment by henopied** [comment]
That's because it never actually disconnects you from the old server.

**Comment by heroandtn3** [comment]
This is a known bug, see #18
