### ISSUE TITLE
Highlight color of current user on leaderboard

### ISSUE THREAD

**Issue by heroandtn3** [SNSA/NEXT#69]
Server only sends an array of leaderboard, all IDs are 0 so it seems we cannot know extractly who is the current user on leaderboard.

**Comment by xzfc** [comment]
Current user have ID = 1.

> it seems we cannot know

If vanilla client can, then we can :)

**Comment by heroandtn3** [comment]
> If vanilla client can, then we can :)

Nice! But why did you close this issue?
