### ISSUE TITLE
Disallow repeat key press events.

### ISSUE THREAD

**Issue by henopied** [SNSA/NEXT#89]

**Comment by heroandtn3** [comment]
Can you explain more?

**Comment by henopied** [comment]
I believe it is best if I show by [example](https://github.com/DnAp/Agar.io-Reverse-Engineering/blob/master/main_out.js#L30-L34). Basically if you hold w it will spam w which isn't that bad but on the other hand if you held down space that would be detrimental to your mass that you have just gained.

**Comment by heroandtn3** [comment]
I totally agree, sometime I get this issue in VNDOT, but that will be nice if we allow to spam W.

**Comment by henopied** [comment]
My next idea would be if we could implement a macro panel like agarplus's.

**Comment by heroandtn3** [comment]
Great!. I think we can keep thing like this, we will consider this later.
